### ISSUE TITLE
Version with no Mario voice lines?

### ISSUE THREAD

**Issue by Concon1231** [MapAnon/sm64-pc-hq-sounds#1]
Not really an issue, more of a request/enhancement but, could you make a version/branch without the HD Mario voice lines so that it's compatible with mods such as Luigi's voice?

**Comment by MapMappening** [comment]
Any sound modding requires the whole sound table to be replaced, no two sound mods can work together.
However you can delete both mario folders and build using that to combine your voice replacing mod with mine.

**Comment by nxfx21** [comment]
i may do this if i can

**Comment by nxfx21** [comment]
@Concon1231 can you send the link to the mod?
